config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  put "pages/register", to: "pages#register", as: "register"

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
require 'net/http'
require 'uri'
require 'json'

class PagesController < ApplicationController
  def home
    @lead = Lead.new
  end

  def register
    @lead = Lead.create(lead_params)
    respond_to do |format|
      if @lead.save
        payload = {
          username:         "New lead!",
          text:             @lead.name + " " + @lead.email + " " + @lead.business.to_s
        }
        uri = URI.parse("https://hooks.slack.com/services/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")
        Net::HTTP.post_form(uri, :payload => JSON.generate(payload))
        format.html { redirect_to root_path, notice: "Thanks! We'll get back to you soon." }
      else
        format.html { redirect_to root_path, alert: "Not registered. Have you entered a correct email?"}
      end
    end
  end

  def lead_params
    params.require(:lead).permit(:name, :email, :business)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- META TAGS -->
  <title>VRConfident, get confident too</title>
  <meta name="description" content="With VRConfident, use Virtual Reality to train and boost your public speaking confidence. Register now for a chance of a free trial!">
  <meta property="og:image" content="http://s3-eu-west-1.amazonaws.com/vrconfident/VRConfident+Public+Speaking+Virtual+Reality+boost+your+confidence.png">

  <!-- FAVICON -->
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>

  <!-- RESPONSIVITY -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- CSS -->
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- GOOGLE ANALYTICS -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77005944-1', 'auto');
  ga('send', 'pageview');

</script>

</head>

<body class='<%= "#{params[:controller]}-#{params[:action]}".gsub('_', '-') %>'>

  <!-- Has to be loaded first for the homepage effects -->
  <%= javascript_include_tag 'application' %>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <div class='site-content'>
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>

  <%= yield :javascript %>

</body>

</html>

app/views/pages/home.html.erb
<script type="text/javascript">
  // Navbar appearance, has to be loaded first
  $('.navbar-wagon-link').addClass("unscrolled")
  $('.navbar-wagon-button').addClass("unscrolled")
  $('.navicon').addClass("unscrolled")
  $('.navicon-small').addClass("unscrolled")
</script>

<!-- BANNER -->

<div class="banner" style="background-image: linear-gradient(-200deg, rgba(0,0,0,0.1) 5%, rgba(0,0,0,0.6) 90%), url(http://s3-eu-west-1.amazonaws.com/vrconfident/VRConfident+-+public+speaking+virtual+reality+banner+resized.jpg);">

  <div class="banner-top"> </div>

  <div class="banner-title text-center">
    <h1 id="headline">WE'VE ALL BEEN THERE.</h1>
  </div>

  <div class="banner-description">
    <p id="intro">Let's face it: public speaking can feel a bit scary at times. Now, what if Virtual Reality could help you train and boost your confidence?</p>
  </div>

  <div class="banner-bottom">
    <div class="angle-down">
      <i class="fa fa-angle-down" id="scrollarrow"></i>
    </div>
  </div>
  <div class="scrollanchor" id="product"></div>

</div>

<!---         WHAT               -->
<div class="wrapper">
  <div class="applybox" style="position: relative;">
    <div class="container text-center padded" >


      <div class="tagline" style="color: white;"><h1>PUBLIC SPEAKING SKILLS TO THE NEXT LEVEL</h1></div>
      <div class="row">

        <div class="col-xs-12 col-sm-4">
          <div class="feature-holder">
            <div class="feature">
              <%= image_tag("immersive experience.png") %>
              <h2>LIVE AN IMMERSIVE EXPERIENCE</h2>
              <p>With VRConfident, live virtual situations of public speaking, in a 3D 360° view.</p>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-sm-4">
          <div class="feature-holder">
            <div class="feature">
              <%= image_tag("test-runs.png") %>
              <h2>ENJOY AS MANY TEST-RUNS AS YOU WANT</h2>
              <p>The public won't even get tired of it, promised! They're virtual anyway.</p>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-sm-4">
          <div class="feature-holder">
            <div class="feature">
              <%= image_tag("experiment.png") %>
              <h2>EXPERIMENT IT ALL TO GET CONFIDENT</h2>
              <p>Train in all situations and settings. You'll finally deliver an incredible presentation!</p>
            </div>
          </div>
        </div>




      </div>
    </div>
    <div style="position: absolute; bottom:70px;" id="howitworks"></div>
  </div>

  <div class="wrapper" style="position: relative">
    <div class="container padded timelinewrapper">
      <div class="tagline"><h1>IT'S AS EASY AS 1, 2, 3</h1></div>
      <%= render 'pages/home/timeline' %>
    </div>
    <div style="position: absolute; bottom:70px;" id="features"></div>
  </div>

  <div class="wrapper">
    <div class="applybox padded">
      <div class="tagline" style="color: white;"><h1>PACKED WITH FEATURES TO MAKE YOU BETTER</h1></div>
      <div class="container">
        <div class="row">

          <div class="col-xs-12 col-sm-4" style="display:flex; justify-content: space-around;">
            <div class='package'>
              <div class='name'>Good</div>
              <div class='price'>€10 / month*</div>
              <div class='trial'>Individuals - free trial</div>

              <ul>
                <li>
                  <strong>3</strong>
                  standard scenes
                </li>
                <li>
                  <strong>Unlimited</strong>
                  number of runs
                </li>
                <li>
                  <strong>Basic analytics</strong>
                  tool suite
                </li>
                <li>
                  <strong>1</strong>
                  user
                </li>
              </ul>
            </div>
          </div>

          <div class="col-xs-12 col-sm-4" style="display:flex; justify-content: space-around;">
            <div class='package brilliant'>
              <div class='name'>Awesome</div>
              <div class='price'>€200 / per week*</div>
              <div class='trial'>Business - free trial</div>
              <ul>
                <li>
                  <strong>5</strong>
                  standard scenes
                </li>
                <li>
                  <strong>Unlimited</strong>
                  number of users
                </li>
                <li>
                  <strong>Unlimited</strong>
                  number of runs
                </li>
                <li>
                  <strong>Virtual Reality</strong>
                  headset
                </li>
                <li>
                  <strong>Full analytics</strong>
                  tools suite
                </li>
              </ul>
            </div>
          </div>

          <div class="col-xs-12 col-sm-4" style="display:flex; justify-content: space-around;">
            <div class='package'>
              <div class='name'>Epic</div>
              <div class='price'>Price on request*</div>
              <div class='trial'>Business - free trial</div>

              <ul>
                <li>
                  <strong>All 'Awesome'</strong>
                  features
                </li>
                <li>
                  <strong>Custom</strong>
                  speaking scenes
                </li>
                <li>
                  <strong>Custom </strong>support
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="wrapper" id="testit">
    <div class="registerbox padded">
      <div class="tagline"><h1>REGISTER NOW, BE IN THE KNOW</h1></div>
      <div class="text-center" style="font-size: 18px;">You'll get to know about our latest product evolutions. Psst: you might also be the first to get your free trial!</div>
      <br>
      <div class="container">

        <div class='form text-center'>

          <%= simple_form_for @lead, :html => {:class => 'form-inline' }, url: register_path, method: :put do |f| %>
          <%= f.input :name, label: 'Name', input_html: { class: 'special' }  %>
          &nbsp;
          <%= f.input :email, :required => true, input_html: { class: 'special' }  %>
          &nbsp;
          <%= f.input :business, label: '  I am a business' %>
          <div>
          </br>
          <%= f.button :submit, 'REGISTER!', :class=> "btn btn-primary" %>
          </div>
          <% end %>
      </div>

    </div>
  </div>
</div>
</div>


<% content_for :javascript do %>
<script>

  // Title dynamic resizing
  $("#headline").fitText(0.8, { minFontSize: '40px', maxFontSize: '70px' });
  $("#intro").fitText(1, { minFontSize: '10px', maxFontSize: '22px' });

  // Banner downarrow effects
  $("#scrollarrow").click(function() {
    $('html, body').animate({
      scrollTop: $("#product").offset().top
    }, 1500);
  });
  function pulse(){
    if($(window).scrollTop() < 100) {
      $("#scrollarrow").animate({fontSize: "+=15"}, 700);
      $("#scrollarrow").animate({fontSize: "-=15"}, 700).delay(3000);
    }
  }
  setInterval(pulse, 3000);

  $(".package").hover(function(){
    $(".package").removeClass("brilliant");
    $(this).toggleClass("brilliant");
  });

</script>
<% end %>

app/views/pages/home/_timeline.html.erb
 <section id="cd-timeline" class="cd-container">

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag("scene.png") %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>1. SET THE SCENE</h2>
      <p>Choose your public speaking setting: sales pitch, corporate meeting, conference, investors pitch, family events...For business customers, we can 360° shoot actual meeting rooms and colleagues, for maximum immersion </p>
    </div> <!-- cd-timeline-content -->
  </div> <!-- cd-timeline-block -->

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag "rehearse.png", :class => "playlogo" %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>2. REHEARSE, REHEARSE</h2>
      <p>With the Virtual Reality headset on, present to your virtual audience as if you were facing a real crowd. This breathtaking experience will train you as the real event, and boost your confidence for your actual presentation  </p>
    </div> <!-- cd-timeline-content -->
  </div> <!-- cd-timeline-block -->

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag("feedback.png") %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>3. GET FEEDBACK</h2>
      <p>Leverage built-in coaching tools to improve your presentation: timer, "uuuh"-counter, look direction analyser, and other features to come! </p>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

  </section> <!-- cd-timeline -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class = "footerbox">
          <p>
            *subject to change as product evolves
          </p>

          <p>
            2016 VRConfident, a concept propelled by <%= link_to "Thomas Vanderstraeten", "http://be.linkedin.com/in/thomas-vanderstraeten-5710a148" %> in Brussels, BE
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to image_tag('VRConfident logo.png'), root_path, id:"logo", class: "navbar-wagon-brand" %>

  <!-- Right Navigation, hidden on mobile -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

  <%= link_to "INTRO", "#", class: "navbar-wagon-item navbar-wagon-link"%>

    <%= link_to "PRODUCT", "#product", class: "navbar-wagon-item navbar-wagon-link"%>

    <%= link_to "HOW IT WORKS", "#howitworks", class: "navbar-wagon-item navbar-wagon-link"%>

    <%= link_to "FEATURES & PRICING", "#features", class: "navbar-wagon-item navbar-wagon-link"%>

    <%= link_to "FREE TRIAL", "#testit", class: "navbar-wagon-item navbar-wagon-link" %>
  </div>
  <!-- end of right navigation -->

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg" style="display: flex; justify-content: space-around">
    <div class="dropdown">
      <i class="navicon fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "INTRO", "#" %></li>
        <li><%= link_to "PRODUCT", "#product" %></li>
        <li><%= link_to "HOW IT WORKS", "#howitworks" %></li>
        <li><%= link_to "FEATURES & PRICING", "#features" %></li>
        <li><%= link_to "FREE TRIAL", "#testit" %></li>
      </ul>
    </div>
  </div>
  <!-- end of mobile-only dropdown -->
</div>